Expose, Themenfeldanalyse und Titel | Tim Loges
cnoss/thesis-old pull request #12
Opened 2023-03-21 20:32 UTC by WasMachenSachen

- Themenfeldanalyse um Prozess und Internationalisierung ergänzt
- Titel Vorschläge angelegt
- Erster Entwurf Expose

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +1. Entwicklung eines Vorgehens zur automatisierten Generierung von Beschreibungstexten für Online-Shops auf Basis strukturierter Produkteigenschaften, als Plugin zur Integration in Shopsystemen und V
gut

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +3. Entwicklung eines Plugins für die automatische Generierung von Beschreibungstexten im E-Commerce Bereich, mithilfe von vortrainierten Sprachmodellen (anhand strukturierter Produktdaten).
auch gut

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +4. Entwicklung eines Plugins zur automatisierten Generierung von Beschreibungstexten in Online-Shops, auf Basis von strukturierten Produktdaten aus der Produktkategorie "Wein".
auch gut :)

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +8. Entwicklung einer automatisierten Lösung zur Generierung von Beschreibungstexten für Wein im E-Commerce Bereich auf Basis strukturierter Produktdaten.
auch gut

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +8. Entwicklung einer automatisierten Lösung zur Generierung von Beschreibungstexten für Wein im E-Commerce Bereich auf Basis strukturierter Produktdaten.
wäre mein fav

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +1. Welches Sprachmodell eignet sich für die automatische Generierung von Beschreibungstexten?
ja … ggf. mit Ergänzung «Generierung aus strukturierten Produktmerkmalen»

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +2. Welche Qualitätskriterien werden benötigt, um automatisch generierte Beschreibungstexte zu Bewerten?
Eher Kriterien, statt Qualikriterien.

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +   1. Gibt es Unterschiede bei den Qualitätskriterien, wenn sich die Zielgruppe ändert?
Wäre SEO auch eine "Zielgruppe"?

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +3. Wie kann die Qualität der Beschreibungstexte objektiv gemessen werden?
ich glaub Objektivität ist hier wenig hilfreich … siehe frage davor, denn Letztendes entscheidet das Subjekt, ob der text hilft… Aber vielleicht könnte ein Tool/ Plugin auch mehrere Vorschläge in verschiedenen Tonalitäten erzeugen und Redakteur entscheidet, was gerade in die Zeit, zum Produkt, etc passt.

2023-03-29 09:40 UTC, cnoss commented on _works/t-loges/02-titles-and-research-questions.md
> +6. Muss die Generierung der Beschreibungstexte voll-automatisiert funktionieren oder kann ein semi- bzw. teil-automatisierter Vorgang bereits Experten/Editoren unterstützen?
schwer zu beantworten

2023-04-04 08:29 UTC, WasMachenSachen commented on _works/t-loges/02-titles-and-research-questions.md
> +   1. Gibt es Unterschiede bei den Qualitätskriterien, wenn sich die Zielgruppe ändert?
Ich hätte SEO erstmal hinten angestellt. Ich gehe davon aus, dass wir keine (großen) Unterschiede im Ranking erreichen durch Produktbeschreibungen.

2023-04-04 08:31 UTC, WasMachenSachen commented on _works/t-loges/02-titles-and-research-questions.md
> +3. Wie kann die Qualität der Beschreibungstexte objektiv gemessen werden?
Tonalitäten/Stimmungen finde ich eine gute Ergänzung.

2023-04-04 08:36 UTC, WasMachenSachen commented on _works/t-loges/02-titles-and-research-questions.md
> +8. Entwicklung einer automatisierten Lösung zur Generierung von Beschreibungstexten für Wein im E-Commerce Bereich auf Basis strukturierter Produktdaten.
dann würde ich mit dem Titel loslegen

2023-04-06 14:24 UTC, cnoss requested changes

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +# Exposé "Entwicklung einer automatisierten Lösung zur Generierung von Beschreibungstexten für Wein im E-Commerce Bereich auf Basis strukturierter Produktdaten"
vielleicht besser: Konzeption und Entwicklung

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +Beschreibungstexte sind ein wichtiger Bestandteil der Kaufentscheidung im E-Commerce Bereich. Hier gilt es, potenzielle Kunden über ein Produkt und ihre Merkmale aufzuklären, um einen Kaufwunsch einz
"Beschreibungstexte sind ein wichtiger Bestandteil der Kaufentscheidung im E-Commerce Bereich." – These … hier muss ein Beleg her. :)

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +Die strukturierten Produktdaten kommen vom Großhandel und enthalten Informationen über Region, Rebsorte, Charakteristiken etc.
Hier sollte "Strukturierte Produktdaten" kurz eingeführt und bebeispielt werden.

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +Ebenfalls gilt es, durch Experten aus dem Bereich des Weinhandels zu Evaluieren, inwiefern sich die generierten Texte eignen, um Weine zu Beschreiben. Hierfür stellt der externe Partner dieser Arbeit
Kontext sollte man weiter oben kurz vorstellen: das es einen Koop-Partner gibt und was der so macht. Und ggf. auch, dass die Texte ein Painpoint sind und warum.

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +Um die Nutzung für die Redakteure zu ermöglichen, soll ein Plugin für Shopware 6 entstehen. Hier sind zwei Punkte interessant: Wie muss das User Interface gestaltet sein, damit Editoren effizient Tex
Welche Redakteure? Bislang nicht eingeführt.

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +Diese Arbeit entsteht zusammen mit dem externen Partner Gjuce. Gjuce ist eine Webagentur aus Köln, welche unter anderem Shops im Bereich des Weinhandels betreut und daher mit Expertise unterstützen k
Ah :) Vielleicht besser weiter vorne, verbessert die Street Credibility

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +1. Welches Sprachmodell eignet sich für die automatische Generierung von Beschreibungstexten aus strukturierten Produktmerkmalen?
Vielleicht besser: eignet sich am Besten

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +2. Welche Kriterien werden benötigt, um automatisch generierte Beschreibungstexte zu Bewerten?
Vielleicht: Auf Basis welcher Kriterien lassen sich …

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +   1. Gibt es Unterschiede bei den Kriterien, wenn sich die Zielgruppe ändert?
als eine Frage mit 2. konstruieren

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +- Einleitung
Kontext bitte mit in die Einleitung

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +- Grundlagen
Passt hier nicht … ich selbst mag aktive Kapitelnamen – sprich mit Verben

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +  - _E-Commerce Allgmein?_
Eher Weinhandel  und darin dann die E-Com Varianten

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +  - Shopware und Plugin Ecosystem
Redaktionsprozess würde mir noch fehlen

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +- Plugin Entwicklung
was passiert hier?

2023-04-06 14:24 UTC, cnoss commented on _works/t-loges/03-expose.md
> +- Plugin Entwicklung
Wo und wie werden Kriterien entwickelt?

2023-04-10 12:37 UTC, WasMachenSachen commented on _works/t-loges/03-expose.md
> +- Plugin Entwicklung
Ich bin noch nicht tief genug in Shopware und das Plugin Ecosystem eingedrungen, daher bin ich noch nicht sicher welche Schritte nötig sind. Im besten Fall kann das Plugin so weit wie Möglich unabhängig von Shopware funktionieren.
 Folgende Schritte sehe ich auf jeden Fall innerhalb der Entwicklung bzw. Implementierung (neuer Kapitelname):
- Tech-Stack wählen/darlegen
- Plugin aufsetzen 
- Anbindung an das Sprachmodell
- Anbindung mit Shopware

Auch möglich ist ein erstes POC in Figma, um Validierung durch Redakteure schon vorziehen zu können.

2023-05-10 06:55 UTC, merged