Praxisprojekt Multiscreen Interaction Game
cnoss/thesis-old pull request #16
Opened 2023-05-19 10:59 UTC by fberghahn

Neue Titel und Forschungsfragen, sowie den überarbeiteten Themenfeldcluster, hinzugefügt.

Beste Grüße 
Florian Berghahn

2023-06-07 07:12 UTC, cnoss requested changes

2023-06-07 07:12 UTC, cnoss commented on _works/2023-berghahn-florian/03-expose.md
> +In der heutigen Zeit wird Software immer häufiger über mehrere Geräte gleichzeitig
"In der heutigen Zeit" ist journalistischer, aber kein wissenschaftlicher Stil

2023-06-07 07:12 UTC, cnoss commented on _works/2023-berghahn-florian/03-expose.md
> +zu wechseln, für viele Benutzer immer wichtiger wird. Außerdem ist mit der zuneh-
Hierzu gibt es auf jeden Fall Zahlen/ Statistiken … bei rein packen

2023-06-07 07:12 UTC, cnoss commented on _works/2023-berghahn-florian/03-expose.md
> +Complementarity Pattern beschrieben.
Hier können 2 - 3 Beispiele helfen

2023-06-07 07:12 UTC, cnoss commented on _works/2023-berghahn-florian/03-expose.md
> +für fast alle Endgeräte bietet und eine Starthürde wie z.B eine Installation vermieden
installation von was?

2023-06-07 07:12 UTC, cnoss commented on _works/2023-berghahn-florian/03-expose.md
> +und einfache Zug ̈anglichkeit auch besonders wichtig.
Satz verstehe ich nicht. Was ist die Aussage?

2023-06-15 12:22 UTC, fberghahn commented
@cnoss ich habe das Exposé an den angemerkten Stellen überarbeitet, bitte um Feedback.
MFG Florian Berghahn

2023-11-08 06:22 UTC, merged