Exposé Tobias Rutsch
cnoss/thesis-old pull request #19
Opened 2023-06-13 12:51 UTC by TobiasRutsch

Exposé hinzugefügt.

2023-06-14 11:37 UTC, cnoss requested changes

2023-06-14 11:37 UTC, cnoss commented on _works/t-rutsch/expose.md
> +So lassen sich mittels AI-unterstützer Tools beispielsweise automatisiert Grafiken erstellen, die der Bildwelt des Unternehmens oder des beworbenen Produkts entsprechen, sodass zum Beispiel auf aufwe
konkrete Bildbeispiele wären schön

2023-06-14 11:37 UTC, cnoss commented on _works/t-rutsch/expose.md
> +Um untersuchen zu können welche möglichen Einsatzgebiete für AI-Tools zur automatisierten Grafikerstellung und -ergänzung im Online-Marketing in Frage kommen, wird zunächst untersucht wie Grafiken im
Um untersuchen zu können welche möglichen Einsatzgebiete für AI-Tools zur automatisierten Grafikerstellung und -ergänzung im Online-Marketing in Frage kommen, wird zunächst untersucht wie Grafiken im Online-Marketing verwendet werden -> wie wird das untersucht? Methode(n)? Gibt es Arbeiten dazu?

2023-06-14 11:37 UTC, cnoss commented on _works/t-rutsch/expose.md
> +Um untersuchen zu können welche möglichen Einsatzgebiete für AI-Tools zur automatisierten Grafikerstellung und -ergänzung im Online-Marketing in Frage kommen, wird zunächst untersucht wie Grafiken im
welche Regeln und Faktoren dabei zu beachten sind und welche Anforderungen dafür gelten. -> Woher kommen diese? Woraus werden diese abgeleitet? Ist das generisch gemeint (Branchen)? Könnte seeeeeeeeehr groß werden.

2023-06-14 15:00 UTC, TobiasRutsch commented on _works/t-rutsch/expose.md
> +So lassen sich mittels AI-unterstützer Tools beispielsweise automatisiert Grafiken erstellen, die der Bildwelt des Unternehmens oder des beworbenen Produkts entsprechen, sodass zum Beispiel auf aufwe
Alles klar, werde ich ergänzen. müssen diese Beispiele slebst erarbeitet sein oder reichen da Beispiele, die auch die Tool-Betreiber nutzen?

2023-06-14 15:38 UTC, TobiasRutsch commented on _works/t-rutsch/expose.md
> +Um untersuchen zu können welche möglichen Einsatzgebiete für AI-Tools zur automatisierten Grafikerstellung und -ergänzung im Online-Marketing in Frage kommen, wird zunächst untersucht wie Grafiken im
Die Einsatzgebiete von Grafiken in Online Marketing sollen via Literaturrecherche herausgestellt werden. Arbeiten, die das Thema (zum Teil) behandeln, findet man teilweise in der aufgehührten Literatur. Dazu kann ich gerne auch hier konkrete Literatur ergänzen. 
Grundsätzlich soll auf typische (generische) Anwendungsfälle im Online-Marketing eingegangen werden. Dabei sollen die Regeln und Faktoren sowie Anforderungen dieser sich jeweils lediglich auf die Erfüllung des Anwendungsfalls beziehen und auch aus der Literaturrecherche erfolgen. 

Alternativ könnten auch reale Anwendungsfälle aus dem Unternehmen SHOP-APOTHEKE EUROPE untersucht werden, für das ich tätig bin. Durch konkrete Anwendungsfälle würde auch die Branche eingegrenzt, da auch reale Anfroderungen etc. existieren. Dafür müsste ich allerdings vorher klären in welcher Form die Anwendungsfälle dokumntiert sein müssten und diese beim Unternehmen anfragen.

2023-06-28 06:27 UTC, cnoss requested changes

2023-06-28 06:27 UTC, cnoss commented on _works/t-rutsch/expose.md
> +So lassen sich mittels AI-unterstützer Tools beispielsweise automatisiert Grafiken erstellen, die der Bildwelt des Unternehmens oder des beworbenen Produkts entsprechen, sodass zum Beispiel auf aufwe
Müssen nicht selbst erarbeitet sein

2023-06-28 06:27 UTC, cnoss commented on _works/t-rutsch/expose.md
> +Um untersuchen zu können welche möglichen Einsatzgebiete für AI-Tools zur automatisierten Grafikerstellung und -ergänzung im Online-Marketing in Frage kommen, wird zunächst untersucht wie Grafiken im
Eingrenzung find ich gut

2023-07-03 15:09 UTC, TobiasRutsch commented
Die besprochenen Änderungen wurden nun umgesetzt.

2023-07-19 06:13 UTC, cnoss approved these changes

2023-07-19 06:13 UTC, merged