Expose von Felix Guenthner
cnoss/thesis-old pull request #25
Opened 2023-07-26 16:54 UTC by Felix2019

2023-07-28 05:54 UTC, cnoss requested changes

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +2. Augmented Reality für Flutter Web: Entwicklung eines Plugins anhand eines Praxisbeispiels
Das wäre mein Fav

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +5. Wie und warum wird der Anwendungsfall für die Implementierung von Augmented Reality in einer Flutter Web App bestimmt und welche Aspekte der Augmented Reality werden hierbei besonders fokussiert?
Würde ich weg lassen

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +2. Was sind die Herausforderungen und Hürden bei der Entwicklung eines Augmented Reality Plugins für Flutter Web und wie können diese gelöst werden?
Aus meiner Sicht sollte das Frage 1 sein

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +1. Wie kann ein Augmented Reality Plugin in Flutter Web unter Verwendung der WebXR-API effektiv implementiert werden?
Streichen

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +3. Welche spezifischen Anforderungen hat der ausgewählte Anwendungsfall an das Augmented Reality Plugin und wie können diese erfüllt werden?
Nicht ganz so glücklich formuliert, aber im Prinzip gut

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/02-titles-and-research-questions.md
> +4. Wie kann eine robuste und wirksame Fallback-Lösung für den Fall eines Misserfolgs bei der Implementierung des Augmented Reality Plugins entworfen und implementiert werden?
Streichen

2023-07-28 05:54 UTC, cnoss commented on _works/f-guenthner/03-expose.md
> +In einer bereits entwickelten Progressive Web App, die mit dem Framework Flutter umgesetzt wurde, ist bei der Konzeption und Implementierung von neuen Anwendungsfällen ein Problem aufgetreten. Die An
Bissl umständlich formuliert … vielleicht eher: Eine bestehende Dating App soll um das Feature „Virtuelle Geschenke“ erweitert werden. Diese Geschenke sollen als … 

2023-08-08 13:35 UTC, Felix2019 commented
Neue Version mit den Änderungen ist da.

2023-08-16 05:36 UTC, merged