Themenfeldcluster Update und Exposé
cnoss/thesis-old pull request #7
Opened 2023-02-04 17:01 UTC by Snapstromegon

Das Themenfeldcluster wurde aktualisiert um den Fokus zu spezifizieren.
Zusätzlich wurde eine erste Fassung des Exposé erarbeitet.

2023-02-06 14:03 UTC, cnoss requested changes
Bitte Kommentare checken und entsprechend überarbeiten.

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +Webentwicklung ist ein sehr schnellebiges und dynamisches Entwicklungsfeld, dass gerade in den letzten Jahren durch neue Features wie die sogenannten "Fugu"-APIs oder die Einführung von Progressive W
- Webentwicklung ist ein sehr schnellebiges und dynamisches Entwicklungsfeld - Beleg fehlt. wer sagt das?
- "Fugu"-APIs - Sollte kurz erklärt werden.
- sich stark gewandelt - Beleg fehlt. Wer sagt das?
- Leider ist - bewertend. Bitte neutral fomrulieren

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +Als WebentwicklerIn gibt dies das Problem auf, dass man sich nicht darauf verlassen kann, dass nur weil etwas standardisiert ist, man es nutzen kann. Sollte man mit potentiell neuen Technologien expl
- Als WebentwicklerIn gibt dies das Problem auf - komische Formulierung
- dass man sich nicht darauf verlassen kann, dass nur weil etwas standardisiert ist - besser formulieren bitte

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +2. Gibt es bei Frage 1. Abweichung je nach "Bereich" eines Features?
Bereich - müsste hier definiert/ erklärt werden

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +Glücklicherweise existieren bereits einige sehr umfassende Datenquellen mit historischem Browsersupport für jedes Feature wie [wpt.fyi], [caniuse] oder [mdn-browser-compat-data]. Diese Quellen können
- Glücklicherweise - wertend

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +Gleichzeitig ist es möglich die Veröffentlichungen der Standards mit zum Beispiel GitHub Repositories heranzuziehen um nachzuvollziehen wann Features standardisiert wurden und wie sie sich entwickelt
"Gleichzeitig ist es möglich die Veröffentlichungen der Standards mit zum Beispiel GitHub Repositories heranzuziehen um nachzuvollziehen wann Features standardisiert wurden und wie sie sich entwickelt haben." - hier fehlt mir das ein oder andere Komma, um den Satz zu verstehen.

2023-02-06 14:03 UTC, cnoss commented on _works/r-hoeser/03-expose.md
> +[Interop]: https://wpt.fyi/interop-2023
Bitte unbedingt vorab mal Korrekturlesen (lassen!). Da sind mega viele orthographische und Satzbau Fehler drin!

2023-02-06 15:39 UTC, Snapstromegon commented on _works/r-hoeser/03-expose.md
> +Webentwicklung ist ein sehr schnellebiges und dynamisches Entwicklungsfeld, dass gerade in den letzten Jahren durch neue Features wie die sogenannten "Fugu"-APIs oder die Einführung von Progressive W
Anmerkungen eingearbeitet.

2023-02-06 15:39 UTC, Snapstromegon commented on _works/r-hoeser/03-expose.md
> +Als WebentwicklerIn gibt dies das Problem auf, dass man sich nicht darauf verlassen kann, dass nur weil etwas standardisiert ist, man es nutzen kann. Sollte man mit potentiell neuen Technologien expl
Formulierung ausgebessert

2023-02-06 15:40 UTC, Snapstromegon commented on _works/r-hoeser/03-expose.md
> +2. Gibt es bei Frage 1. Abweichung je nach "Bereich" eines Features?
Hier habe ich eine Anmerkung hinzugefügt, dass "Bereich" in Frage 8 ausgearbeitet werden soll. Reicht das?

2023-02-06 15:40 UTC, Snapstromegon commented on _works/r-hoeser/03-expose.md
> +Glücklicherweise existieren bereits einige sehr umfassende Datenquellen mit historischem Browsersupport für jedes Feature wie [wpt.fyi], [caniuse] oder [mdn-browser-compat-data]. Diese Quellen können
Wurde umformuliert

2023-02-06 15:43 UTC, Snapstromegon commented
Das Exposé wurde basierend auf den Anmerkungen aktualisiert.
Allgemeine Frage:
Soll ich Kommentare nach Bearbeitung "resolven", oder machen Sie das (aus dem professionellen Umfeld kenne ich die Regel, dass der Kommentarersteller Anmerkungen resolved, möchte nur sicher gehen ob das hier genauso gehandhabt wird)?

2023-02-21 10:38 UTC, cnoss approved these changes

2023-02-21 10:39 UTC, merged